name: Deploy to Amplify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      - name: Initialize Amplify environment
        run: amplify init --appId d3r706lxlg91q --envName main

      - name: Pull Amplify project
        run: amplify pull --appId d3r706lxlg91q --envName main

      - name: Deploy to Amplify
        run: amplify publish --appId d3r706lxlg91q --envName main
